### ISSUE TITLE
TypeError: expected a string or other character buffer object

### ISSUE THREAD

**Issue by vinay10949** [aetros/aetros-cli#13]
C:\Users\Vinay\Documents\keras>aetros start vinaysawant/kerasCNN
...
Training '1WPX0q0P0' created and started. Open http://aetros.com/trainer/app?tra
ining=1WPX0q0P0 to monitor the training.
start network ...
Using Theano backend.
Setup training
Crashed ...
ERROR:root:Traceback (most recent call last):
  File "c:\anaconda2\lib\site-packages\aetros\starter.py", line 88, in start
    network.job_prepare(job)
  File "c:\anaconda2\lib\site-packages\aetros\network.py", line 130, in job_prep
are
    f.write(config['code'])
TypeError: expected a string or other character buffer object

Sending last (13) monitoring information to server ...
out.
Traceback (most recent call last):
  File "c:\anaconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Anaconda2\Scripts\aetros.exe\__main__.py", line 9, in <module>
  File "c:\anaconda2\lib\site-packages\aetros\__init__.py", line 75, in main
    return command.main(cmd_args)
  File "c:\anaconda2\lib\site-packages\aetros\commands\StartCommand.py", line 45
, in main
    start(parsed_args.network_name, dataset_id=parsed_args.dataset, insights=par
sed_args.insights, insights_sample_path=parsed_args.insights_sample)
  File "c:\anaconda2\lib\site-packages\aetros\starter.py", line 129, in start
    raise e
TypeError: expected a string or other character buffer object

**Comment by marcj** [comment]
Can you please post the script to reproduce? You unfortunately deleted your network, so I can not start it on my test machine.
