### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by anselal** [aetros/aetros-cli#17]
I try to run aetros on windows and get the following error. I did not have any issues when running it from linux. I have keras==1.2.2 installed. I do not know if the error is aetros related or not. Can you provide any feedback ?

Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "c:\python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "c:\python27\lib\site-packages\aetros\commands\ServerCommand.py", line 131, in thread
    if not self.connect():
  File "c:\python27\lib\site-packages\aetros\commands\ServerCommand.py", line 82, in connect
    self.event_listener.fire('registration', server_id)
  File "c:\python27\lib\site-packages\aetros\backend.py", line 87, in fire
    callback(parameter)
  File "c:\python27\lib\site-packages\aetros\commands\ServerCommand.py", line 388, in registration_complete
    self.server.send_message({'type': 'system', 'values': self.collect_system_information()})
  File "c:\python27\lib\site-packages\aetros\commands\ServerCommand.py", line 405, in collect_system_information
    values['disks'][name] = psutil.disk_usage(disk[1]).total
  File "c:\python27\lib\site-packages\psutil\__init__.py", line 2017, in disk_usage
    return _psplatform.disk_usage(path)
  File "c:\python27\lib\site-packages\psutil\_pswindows.py", line 249, in disk_usage
    raise OSError(errno.ENOENT, msg)
OSError: [Errno 2] No such file or directory: 'X:\'

Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\aetros.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\aetros\__init__.py", line 58, in main
    code = command.main(cmd_args)
  File "c:\python27\lib\site-packages\aetros\commands\ServerCommand.py", line 301, in main
    self.server.send_message({'type': 'utilization', 'values': self.collect_system_utilization()})
  File "c:\python27\lib\site-packages\aetros\commands\ServerCommand.py", line 434, in collect_system_utilization
    values['disks'][name] = psutil.disk_usage(disk[1]).used
  File "c:\python27\lib\site-packages\psutil\__init__.py", line 2017, in disk_usage
    return _psplatform.disk_usage(path)
  File "c:\python27\lib\site-packages\psutil\_pswindows.py", line 249, in disk_usage
    raise OSError(errno.ENOENT, msg)
OSError: [Errno 2] No such file or directory: 'X:\'

**Comment by anselal** [comment]
Drive X: is my CDROM drive. I inserted a cd and now I get the following error:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "c:\python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "c:\python27\lib\site-packages\aetros\commands\ServerCommand.py", line 13
1, in thread
    if not self.connect():
  File "c:\python27\lib\site-packages\aetros\commands\ServerCommand.py", line 82
, in connect
    self.event_listener.fire('registration', server_id)
  File "c:\python27\lib\site-packages\aetros\backend.py", line 87, in fire
    callback(parameter)
  File "c:\python27\lib\site-packages\aetros\commands\ServerCommand.py", line 38
8, in registration_complete
    self.server.send_message({'type': 'system', 'values': self.collect_system_in
formation()})
  File "c:\python27\lib\site-packages\aetros\commands\ServerCommand.py", line 40
8, in collect_system_information
    if 0 != id.find('lo') and net.isup:
AttributeError: 'tuple' object has no attribute 'isup'

Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\aetros.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\aetros\__init__.py", line 58, in main
    code = command.main(cmd_args)
  File "c:\python27\lib\site-packages\aetros\commands\ServerCommand.py", line 30
1, in main
    self.server.send_message({'type': 'utilization', 'values': self.collect_syst
em_utilization()})
  File "c:\python27\lib\site-packages\aetros\commands\ServerCommand.py", line 47
4, in collect_system_utilization
    values['loadavg'] = os.getloadavg()
AttributeError: 'module' object has no attribute 'getloadavg'

**Comment by anselal** [comment]
It seems that the client does not run on Windows, since the command os.getloadavg() in only available on Unix systems based on the documentation https://docs.python.org/2/library/os.html#os.getloadavg

**Comment by marcj** [comment]
All those issues should be fixed in version `0.9.9`

**Comment by marcj** [comment]
Thanks for reporting this to us! Currently, we do not officially support Windows (since we do not have any windows developer in the team), however there should not many open issues left.

**Comment by anselal** [comment]
I updated to 0.9.9 and it seems OK now. Thank you !!
