### ISSUE TITLE
Aetros not running on Windows Server 

### ISSUE THREAD

**Issue by floAr** [aetros/aetros-cli#26]
When starting the aetros cli it produces:
```
[0m [34maetros-server[3912][0m [30mERROR[0m [31mConnection error during connecting to trainer.aetros.com: preexec_fn is not supported on Windows platforms[0m
Exception in thread Thread-3:
Traceback (most recent call last):
  File "c:\anaconda\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "c:\anaconda\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "c:\anaconda\lib\site-packages\aetros\backend.py", line 347, in thread_write
    if not self.connect():
  File "c:\anaconda\lib\site-packages\aetros\backend.py", line 210, in connect
    stdout=subprocess.PIPE, stdin=subprocess.PIPE, stderr=subprocess.PIPE)
  File "c:\anaconda\lib\subprocess.py", line 343, in __init__
    raise ValueError("preexec_fn is not supported on Windows "
ValueError: preexec_fn is not supported on Windows platforms
```

**Comment by marcj** [comment]
This is because Windows is currently not supported, but we're working on it. In the next release probably end of the week we release some fixes for windows issue like that.
