### ISSUE TITLE
Crash when running on regression task

### ISSUE THREAD

**Issue by almathie** [aetros/aetros-cli#5]
Aetros integration makes my regression DNN crash when performing the fit operation.

Here is the stack trace :

```
File "downloads.py", line 40, in <module>
    model.fit(X, Y, validation_split=0.2, nb_epoch=1000, batch_size=10, callbacks=callbacks_list, verbose=1)
  File "/usr/local/lib/python2.7/dist-packages/aetros/KerasIntegration.py", line 54, in overwritten_fit
    class_weight, sample_weight, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 597, in fit
    sample_weight=sample_weight)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1107, in fit
    callback_metrics=callback_metrics)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 845, in _fit_loop
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python2.7/dist-packages/keras/callbacks.py", line 40, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/usr/local/lib/python2.7/dist-packages/aetros/KerasLogger.py", line 162, in on_epoch_end
    log['validation_accuracy'][layer.name] = log['val_acc'] #outs[1]
KeyError: 'val_acc
```

Here is the script :

```
# create model
model = Sequential()
model.add(Dense(34, input_dim=47, init='normal', activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(23, init='normal', activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(12, init='normal', activation='relu'))
model.add(Dense(1, init='normal', activation='linear'))
# Compile model
model.compile(loss='mean_absolute_percentage_error', optimizer='adam')

# Save best weigths
filepath="weights.best.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='val_loss', verbose=0, save_best_only=True, mode='min')
callbacks_list = [checkpoint]

# Add Aetros integration
from aetros.KerasIntegration import KerasIntegration
KerasIntegration('almathie/downloads', model, insights=True)

model.fit(X, Y, validation_split=0.2, nb_epoch=1000, batch_size=10, callbacks=callbacks_list, verbose=1)
```

Note that running the script without aetros works just fine

**Comment by arnauddelaunay** [comment]
I hit the same bug but then used the dev version where it has been fixed (with this [commit](https://github.com/aetros/aetros-cli/commit/86daf603a112607be3913e561d369839af3ab408)).
If you installed aetros-cli with pip, first uninstall it and reinstall it using the current master : 

```
sudo pip uninstall aetros
git clone https://github.com/aetros/aetros-cli.git
cd aetros-cli
python setup.py install
```

**Comment by almathie** [comment]
Yep fixed the previous crash, but got another one (same script) :

````
Using Theano backend.
Training status changed to TRAINING 
Train on 93473 samples, validate on 23369 samples
Training status changed to TRAINING 
Epoch 1/1000
93420/93473 [============================>.] - ETA: 0s - loss: 1893645.5566Traceback (most recent call last):
  File "downloads.py", line 45, in <module>
    model.fit(X, Y, validation_split=0.2, nb_epoch=1000, batch_size=10, callbacks=callbacks_list, verbose=1)
  File "/usr/local/lib/python2.7/dist-packages/aetros-0.3.4-py2.7.egg/aetros/KerasIntegration.py", line 55, in overwritten_fit
    class_weight, sample_weight, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 597, in fit
    sample_weight=sample_weight)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1107, in fit
    callback_metrics=callback_metrics)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 845, in _fit_loop
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python2.7/dist-packages/keras/callbacks.py", line 40, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/usr/local/lib/python2.7/dist-packages/aetros-0.3.4-py2.7.egg/aetros/KerasLogger.py", line 215, in on_epoch_end
    images = self.build_insight_images()
  File "/usr/local/lib/python2.7/dist-packages/aetros-0.3.4-py2.7.egg/aetros/KerasLogger.py", line 326, in build_insight_images
    image = self.make_image_from_dense(np.squeeze(Y))
  File "/usr/local/lib/python2.7/dist-packages/aetros-0.3.4-py2.7.egg/aetros/KerasLogger.py", line 484, in make_image_from_dense
    cols = int(math.ceil(math.sqrt(len(neurons))))
TypeError: len() of unsized object
````

**Comment by marcj** [comment]
@almathie we fixed it in current master. Please try this version again.
